In [24]:
import pandas as pd
import numpy as np
import warnings 
warnings.filterwarnings('ignore')

# EXPLORATORY DATA ANALYSIS AND DATA CLEANING

In [25]:
df = pd.read_csv("amazon_products_sales_data_cleaned.csv")
df.head()

,product_title,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category,discount_percentage
0,BOYA BOYALINK 2 Wireless Lavalier Microphone f...,4.6,375.0,300.0,89.68,159.00,No Badge,Sponsored,Save 15% with coupon,Add to cart,2025-09-01,Carbon impact,https://m.media-amazon.com/images/I/71pAqiVEs3...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Phones,43.60
1,"LISEN USB C to Lightning Cable, 240W 4 in 1 Ch...",4.3,2457.0,6000.0,9.99,15.99,No Badge,Sponsored,No Coupon,Add to cart,2025-08-29,NaN,https://m.media-amazon.com/images/I/61nbF6aVIP...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,37.52
2,"DJI Mic 2 (2 TX + 1 RX + Charging Case), Wirel...",4.6,3044.0,2000.0,314.00,349.00,No Badge,Sponsored,No Coupon,Add to cart,2025-09-01,NaN,https://m.media-amazon.com/images/I/61h78MEXoj...,https://www.amazon.com/sspa/click?ie=UTF8&spc=...,2025-08-21 11:14:29,Laptops,10.03
3,"Apple AirPods Pro 2 Wireless Earbuds, Active N...",4.6,35882.0,10000.0,162.24,162.24,Best Seller,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61SUj2aKoE...,https://www.amazon.com/Apple-Cancellation-Tran...,2025-08-21 11:14:29,Phones,0.00
4,Apple AirTag 4 Pack. Keep Track of and find Yo...,4.8,28988.0,10000.0,72.74,72.74,No Badge,Organic,No Coupon,NaN,NaN,NaN,https://m.media-amazon.com/images/I/61bMNCeAUA...,https://www.amazon.com/Apple-MX542LL-A-AirTag-...,2025-08-21 11:14:29,Phones,0.00

In [26]:
df.tail()

,product_title,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,is_best_seller,is_sponsored,has_coupon,buy_box_availability,delivery_date,sustainability_tags,product_image_url,product_page_url,data_collected_at,product_category,discount_percentage
42670,"Elgato 4K Pro, Internal Capture Card: 8K60 Pas...",5.0,1.0,100.0,195.99,195.99,No Badge,Organic,No Coupon,NaN,2025-09-04,NaN,https://m.media-amazon.com/images/I/51KCB+egEs...,https://www.amazon.com/Elgato-4K-Pro-Internal-...,2025-08-30 19:56:33,TV & Display,0.00
42671,"Arlo Essential Spotlight Camera, Wireless Secu...",4.2,20.0,200.0,89.99,89.99,No Badge,Organic,Save $25.00 with coupon,Add to cart,2025-09-04,NaN,https://m.media-amazon.com/images/I/51jV+o1LZE...,https://www.amazon.com/Arlo-Essential-Spotligh...,2025-08-30 19:56:33,Cameras,0.00
42672,"GIGABYTE - AORUS FO32U2-32"" QD OLED Gaming Mon...",4.3,57.0,50.0,899.99,1099.99,Save 18%,Organic,No Coupon,Add to cart,2025-09-04,NaN,https://m.media-amazon.com/images/I/71ySPkNLkG...,https://www.amazon.com/GIGABYTE-FO32U2-32-3840...,2025-08-30 19:56:33,Chargers & Cables,18.18
42673,Monoprice XLR Male to 1/4-Inch TRS Male Cable ...,4.7,7102.0,500.0,10.39,15.98,No Badge,Organic,No Coupon,Add to cart,2025-09-04,NaN,https://m.media-amazon.com/images/I/411c0JFJ79...,https://www.amazon.com/Monoprice-XLR-Male-4-In...,2025-08-30 19:56:33,Chargers & Cables,34.98
42674,Lorex Fusion 1080p HD Security Camera System w...,4.4,75.0,50.0,419.99,499.99,No Badge,Organic,No Coupon,Add to cart,2025-09-04,NaN,https://m.media-amazon.com/images/I/71wTn+zoSr...,https://www.amazon.com/Lorex-8-Channel-Securit...,2025-08-30 19:56:33,Cameras,16.00

In [27]:
df.shape

(42675, 17)

In [28]:
df.columns

Index(['product_title', 'product_rating', 'total_reviews',
       'purchased_last_month', 'discounted_price', 'original_price',
       'is_best_seller', 'is_sponsored', 'has_coupon', 'buy_box_availability',
       'delivery_date', 'sustainability_tags', 'product_image_url',
       'product_page_url', 'data_collected_at', 'product_category',
       'discount_percentage'],
      dtype='str')

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 42675 entries, 0 to 42674
Data columns (total 17 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   product_title         42675 non-null  str
 1   product_rating        41651 non-null  float64
 2   total_reviews         41651 non-null  float64
 3   purchased_last_month  32164 non-null  float64
 4   discounted_price      40613 non-null  float64
 5   original_price        40613 non-null  float64
 6   is_best_seller        42675 non-null  str
 7   is_sponsored          42675 non-null  str
 8   has_coupon            42675 non-null  str
 9   buy_box_availability  28022 non-null  str
 10  delivery_date         30692 non-null  str
 11  sustainability_tags   3408 non-null   str
 12  product_image_url     42675 non-null  str
 13  product_page_url      40606 non-null  str
 14  data_collected_at     42675 non-null  str
 15  product_category      42675 non-null  str
 16  discount_percentage   40613 non-null  float64
dtypes: float64(6), str(11)
memory usage: 38.8 MB

In [30]:
df.describe()

,product_rating,total_reviews,purchased_last_month,discounted_price,original_price,discount_percentage
count,41651.000000,41651.000000,32164.000000,40613.000000,40613.000000,40613.000000
mean,4.399431,3087.106000,1293.665278,243.227289,257.611107,6.547151
std,0.386997,13030.460133,6318.323574,473.351545,496.633495,12.744715
min,1.000000,1.000000,50.000000,2.160000,2.160000,0.000000
25%,4.200000,82.000000,100.000000,29.690000,32.990000,0.000000
50%,4.500000,343.000000,200.000000,84.990000,89.000000,0.000000
75%,4.700000,1886.000000,400.000000,224.000000,229.990000,8.490000
max,5.000000,865598.000000,100000.000000,5449.000000,5449.000000,85.420000

In [31]:
df.isnull().sum()

product_title               0
product_rating           1024
total_reviews            1024
purchased_last_month    10511
discounted_price         2062
original_price           2062
is_best_seller              0
is_sponsored                0
has_coupon                  0
buy_box_availability    14653
delivery_date           11983
sustainability_tags     39267
product_image_url           0
product_page_url         2069
data_collected_at           0
product_category            0
discount_percentage      2062
dtype: int64

## DATA CLEANING AND NULL HANDLING

In [32]:
#Fill missing purchases with 0
df['purchased_last_month'] = df['purchased_last_month'].fillna(0)

In [33]:
# fill missing categorical data with descriptive labels
df['sustainability_tags'] = df['sustainability_tags'].fillna('No Tag')
df['buy_box_availability'] = df['buy_box_availability'].fillna('Unknown')

In [34]:
#  Drop Rows with Missing Critical Information
critical_cols = [
    'product_rating', 
    'total_reviews', 
    'discounted_price', 
    'original_price', 
    'discount_percentage',
    'product_page_url'
]

df = df.dropna(subset = critical_cols)

In [35]:
# List the columns that are useless for visualization
useless_columns = [
    'product_image_url', 
    'product_page_url'
]
df = df.drop(columns=useless_columns)

In [36]:
df.isnull().sum()

product_title              0
product_rating             0
total_reviews              0
purchased_last_month       0
discounted_price           0
original_price             0
is_best_seller             0
is_sponsored               0
has_coupon                 0
buy_box_availability       0
delivery_date           9372
sustainability_tags        0
data_collected_at          0
product_category           0
discount_percentage        0
dtype: int64

In [37]:
# now convert to datetime
df['delivery_date'] = pd.to_datetime(df['delivery_date'], errors='coerce')
df['data_collected_at'] = pd.to_datetime(df['data_collected_at'], errors='coerce')

In [38]:
df.info()

<class 'pandas.DataFrame'>
Index: 37587 entries, 0 to 42674
Data columns (total 15 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   product_title         37587 non-null  str
 1   product_rating        37587 non-null  float64
 2   total_reviews         37587 non-null  float64
 3   purchased_last_month  37587 non-null  float64
 4   discounted_price      37587 non-null  float64
 5   original_price        37587 non-null  float64
 6   is_best_seller        37587 non-null  str
 7   is_sponsored          37587 non-null  str
 8   has_coupon            37587 non-null  str
 9   buy_box_availability  37587 non-null  str
 10  delivery_date         28215 non-null  datetime64[us]
 11  sustainability_tags   37587 non-null  str
 12  data_collected_at     37587 non-null  datetime64[us]
 13  product_category      37587 non-null  str
 14  discount_percentage   37587 non-null  float64
dtypes: datetime64[us](2), float64(6), str(7)
memory usage: 11.2 MB

In [39]:
df.isnull().sum()

product_title              0
product_rating             0
total_reviews              0
purchased_last_month       0
discounted_price           0
original_price             0
is_best_seller             0
is_sponsored               0
has_coupon                 0
buy_box_availability       0
delivery_date           9372
sustainability_tags        0
data_collected_at          0
product_category           0
discount_percentage        0
dtype: int64

In [40]:
#nulls date handling with collected date + 9 days
estimated_dates = df['data_collected_at'] + pd.Timedelta(days=9)
df['delivery_date'] = df['delivery_date'].fillna(estimated_dates)

In [41]:
# Clean Text
text_cols = ['product_title', 'is_best_seller', 'is_sponsored', 'has_coupon', 'product_category']
for col in text_cols:
    if df[col].dtype == 'object':
        df[col] = df[col].str.strip()

In [42]:
df.shape

(37587, 15)

In [43]:
df.isnull().sum()

product_title           0
product_rating          0
total_reviews           0
purchased_last_month    0
discounted_price        0
original_price          0
is_best_seller          0
is_sponsored            0
has_coupon              0
buy_box_availability    0
delivery_date           0
sustainability_tags     0
data_collected_at       0
product_category        0
discount_percentage     0
dtype: int64

In [44]:
!pip install pymysql

Requirement already satisfied: pymysql in C:\Users\mohit\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.2.0)

In [46]:
# # NOW LOAD THE DATASET INTO SQL 
# from sqlalchemy import create_engine
# from sqlalchemy.engine import URL
# url_object = URL.create("mysql+mysqlconnector",
# username = 'root',
# password= 'Mohit@7065',
# host = 'localhost',
# database = 'amazon_sales'
# )
# engine = create_engine(url_object)
# table_name = 'amazon_products'
# df.to_sql(name= table_name,con = engine, if_exists= 'replace',index=False)

# f"the database name {database} is sucessfully generated"

In [ ]:
df.to_csv('new_cleaned_dataset', index = False)

In [49]:
df.columns

Index(['product_title', 'product_rating', 'total_reviews',
       'purchased_last_month', 'discounted_price', 'original_price',
       'is_best_seller', 'is_sponsored', 'has_coupon', 'buy_box_availability',
       'delivery_date', 'sustainability_tags', 'data_collected_at',
       'product_category', 'discount_percentage'],
      dtype='str')